### PR TITLE
Nginx remove

### PR DESCRIPTION
**Pull request by talits**
set the config without nginx

### CODE REVIEW

**Comment by raulbcs** [comment]
Hi Talita,

Could you please make some adjustments in this pull request, please? There are some missing information that without it is hard comprehend and be capable of running ansible. Please feel free to add your points if necessary!

All current root folders should be inside a folder, which is the role name - let's name it `qedu-hub`.
Create `hosts` and `playbook.yml` files with the correct informations in them.
In README.md, remove example of `hosts` and `.yml`.

Thanks, Raul

**Comment by raulbcs** [comment]
Hi Talita, thanks for the changes you've made!

Raul

**Comment by talits** [comment]
your welcome ;)

**Comment by marcusesa** [comment]
Hi @Talits, thanks for the latest changes.
About remove nginx, I think we need to remove the following files:
- [main.yml from line 10 to 14](https://github.com/Talits/qedu-hub-ansible/blob/nginx-remove/handlers/main.yml#L10)
- [default.conf](https://github.com/Talits/qedu-hub-ansible/blob/nginx-remove/templates/default.conf)

**Comment by marcusesa** [comment]
Now we only need to remove [default.conf](https://github.com/Talits/qedu-hub-ansible/blob/nginx-remove/templates/default.conf).

**Comment by marcusesa** [comment]
👍

**Pull request merged**
